name: Update Site Screenshots

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */3 *' # https://crontab.guru/every-quarter

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn add puppeteer js-yaml

      - name: Update existing screenshots on scheduled runs
        if: github.event_name == 'schedule'
        run: node site/scripts/takeScreenshots.js update-existing

      - name: Add screenshots for new sites on PRs/push to main and manually dispatched runs
        if: github.event_name != 'schedule'
        run: node site/scripts/takeScreenshots.js

      - name: Push new screenshots
        run: |
          if git diff --quiet site/static/screenshots; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name 'Janosh Riebesell'
          git config user.email janosh.riebesell@gmail.com
          git commit -a -m 'update site screenshots'
          git push
